main: '${project.groupId}.${project.artifactId}.CurrentPlotVisualizerPlugin'
name: '${project.name}'
version: '${project.version}'
api-version: '1.19'
description: 'Visualizes the current Plot.'
author: 'joestr'
website: 'https://github.com/joestr/CurrentPlotVisualizer/'
database: false
softdepend: [PlotSquared]
folia-supported: false
commands:
  currentplotvisualizer:
    description: Shows the help for the PostBox plugin.
    permission: currentplotvisualizer.commands.cpv
    permission-message: '§cYou are lacking permission §fcurrentplotvisualizer.commands.cpv§c!'
    usage: '§cSyntax error! Use: §f/<command>'
permissions:
  currentplotvisualizer.commands.*:
    description: Allows the usage all commands provided by the CurrentPlotVisualizer plugin.
    children:
      currentplotvisualizer.commands.cpv: true